---
- name: Configure wsl with necessary changes
  hosts: localhost
  become: true
  tasks: 
  - name: Install keychain
    apt: 
      name: keychain
      state: latest

  - name: Template out bashrc
    template:
      src: templates/.bashrc.j2
      dest: "/home/oisin/.bashrc"
#      become: true
#      become_user: "{{ ansible_user_id }}"

  - name: Template out networks.conf.j2
    template:
      src: networks.conf.j2
      dest: /etc/vbox/networks.conf
      force: yes

  - name: Set git configuration
    ansible.builtin.template:
      src: .gitconfig.j2
      dest: ~/.gitconfig
      mode: '0644'

  - name: Add vagrant GPG apt Key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
  
  - name: Add the vagrant repository
    apt_repository:
      repo: 'deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
      state: present
  
  - name: Update apt and install vagrant
    apt:
      name: vagrant=2.3.7-1
      state: present
      update_cache: true
